fix basic-workflow.yaml

diff --git a/.github/workflows/basic-workflow.yaml b/.github/workflows/basic-workflow.yaml
--- a/.github/workflows/basic-workflow.yaml
+++ b/.github/workflows/basic-workflow.yaml
@@ -1,4 +1,3 @@
-yaml
 name: Basic Workflow
 on:
   push:
@@ -10,3 +9,7 @@ jobs:
     steps:
       - name: The Thing I've Done
         run: echo "I've done a thing!"
+      - name: An Error I made
+        run: |
+          echo "I've made an error!"
+          exit 1
